# Generated by Django 6.0.2 on 2026-04-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_customuser_fullname_customuser_phone_customuser_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_active_in_booth',
            field=models.BooleanField(default=False),
        ),
    ]
