# Generated by Django 6.0.2 on 2026-04-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_customuser_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_active_guard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='post',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
